//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPIntegrador_PWeb3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncias
    {
        public int IdDenuncia { get; set; }
        public Nullable<int> IdNecesidad { get; set; }
        public Nullable<int> IdMotivo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual MotivoDenuncia MotivoDenuncia { get; set; }
        public virtual Necesidades Necesidades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
